CREATE DATABASE TALLERCHINCHA;
USE TALLERCHINCHA;

CREATE TABLE IF NOT EXISTS MARCAS(
	ID		INT 		AUTO_INCREMENT PRIMARY KEY,
    NOMBRE	VARCHAR(40) UNIQUE NOT NULL 
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS VEHICULOS(
	ID					INT			AUTO_INCREMENT PRIMARY KEY,
    ID_MARCA			INT			NOT NULL,
    MODELO				VARCHAR(40)	NOT NULL,
    COLOR				VARCHAR(40)	NOT NULL,
    COMBUSTIBLE			ENUM('DIESEL','GASOLINA','GLP','GNV','HIBRIDO'),
    ANIO_FABRICACION	CHAR(4) 	NOT NULL,
    CONDICION			ENUM('NUEVO','SEMINUEVO'),
    CONSTRAINT FOREIGN KEY(ID_MARCA) REFERENCES MARCAS(ID)
)ENGINE=INNODB;

INSERT INTO MARCAS(NOMBRE) VALUES('KIA'),('TOYOTA');
SELECT * FROM MARCAS;


INSERT INTO VEHICULOS VALUES 
	(NULL,1,'SORENTO','NEGRO','GASOLINA','2023','SEMINUEVO'),
    (NULL,2,'HILUX','BLANCO','DIESEL','2025','NUEVO');

SELECT * FROM VEHICULOS;

